name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Set up Android SDK and build tools
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;8.7.3"

    - name: Convert Gradlew to Unix line endings
      run: dos2unix ./gradlew

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build the project
      run: ./gradlew build

    - name: Run unit tests and generate reports
      run: ./gradlew test

    - name: Archive unit test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-reports
        path: app/build/reports/tests/testDebugUnitTest/
