name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: '8.7.3'

    - name: Download and Set Gradle Version
      run: |
        wget https://services.gradle.org/distributions/gradle-8.9-bin.zip
        unzip -d /opt/gradle gradle-8.9-bin.zip
        echo "GRADLE_HOME=/opt/gradle/gradle-8.9" >> $GITHUB_ENV
        echo "PATH=$GRADLE_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Convert gradlew to Unix Format
      run: dos2unix ./gradlew

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    - name: Cache Gradle Wrapper
      uses: actions/cache@v3
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest
