name: Android CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Changed from ubuntu-latest to windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Cache Gradle Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 8.7.3
        target: android-35
        min-sdk: 26

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.9'
        
    - name: Run Gradle build
      run: .\gradlew :app:assembleRelease  # Using gradlew.bat on Windows

    - name: Run Unit Tests
      run: .\gradlew testDebugUnitTest  # Using gradlew.bat on Windows

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest/
