name: Android CI Pipeline

on:
  push:
    branches:
      - kotlin_ui_stable_aarati
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Cache Gradle Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35        # Target SDK version (API level 35)
        build-tools: 8.7.3   # Build Tools version 8.7.3
        target: android-35   # Target the correct SDK version
        min-sdk: 26          # Minimum SDK version 26

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.9'  # Your required Gradle version
        
    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew  # Adds execute permissions

    - name: Build Debug APK
      run: bash ./gradlew :WolooSDK:assembleRelease

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/tests/testDebugUnitTest/
