name: Android CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest   # 👈 IMPORTANT (Windows)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Give permission (Windows safe)
      - name: Grant permission
        run: git update-index --chmod=+x gradlew

      # Build using gradlew (will now work)
      - name: Build AAB
        run: .\gradlew.bat bundleRelease

      # Upload AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/*.aab
