name: Android Release Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Release AAB
      - name: Build Release AAB
        run: .\gradlew.bat bundleRelease

      #  Copy AAB to root (clean output)
      - name: Copy AAB to root
        run: |
          $aab = Get-ChildItem -Recurse -Filter *.aab | Select-Object -First 1
          Copy-Item $aab.FullName -Destination app-release.aab

      # Upload only single AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app-release.aab
